import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "../styles/globals.css";
import QueryProvider from "../providers/query-provider";
import { NavBar } from "../components/NavBar";

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"], // มีน้ำหนักให้เลือกเยอะมาก
  variable: "--font-ibm-thai", // ตั้งชื่อตัวแปร CSS ใหม่
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSansThai.variable} font-sans antialiased h-screen grid grid-rows-[auto_1fr] overflow-hidden`} suppressHydrationWarning={true}> {/*แก้ไขเรื่องไปตีกับ extension ใน chrome */}
        <QueryProvider>

          <NavBar />

          <div className="overflow-hidden">
             {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
